<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="..\..\common.props" />
  <Import Project="..\..\configureawait.props" />
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BootstrapBlazor" Version="9.*" />
    <PackageReference Include="BootstrapBlazor.FontAwesome" Version="9.0.*" />
    <PackageReference Include="Volo.Abp.AspNetCore.Components.Web" Version="$(Version)" />
    <PackageReference Include="Volo.Abp.Authorization" Version="$(Version)" />
    <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" Version="$(Version)" />
  </ItemGroup>
  <ItemGroup>
    <_ContentIncludedByDefault Remove="Components\ObjectExtending\ExtensionProperties.razor" />
    <_ContentIncludedByDefault Remove="Components\ObjectExtending\SelectExtensionProperty.razor" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="ConfigureAwait.Fody" Version="3.3.2" />
    <PackageReference Update="Fody" Version="$(FodyVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>