<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
		<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
		<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
		<PreserveCompilationReferences>true</PreserveCompilationReferences>
		<UserSecretsId>BookStore-4681b4fd-151f-4221-84a4-929d86723e4c</UserSecretsId>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Serilog.AspNetCore" Version="8.0.2" />
		<PackageReference Include="Serilog.Sinks.Async" Version="2.0.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\..\modules\Account\Rm.Abp.Account.Web.IdentityServer\Rm.Abp.Account.Web.IdentityServer.csproj" />
		<ProjectReference Include="..\..\..\..\modules\BasicTheme\Rm.Abp.AspNetCore.Mvc.UI.Theme.Basic\Rm.Abp.AspNetCore.Mvc.UI.Theme.Basic.csproj" />
		<ProjectReference Include="..\..\..\..\modules\IdentityManagement\Rm.Abp.IdentityManagement.Blazor.Server.BootstrapBlazorUI\Rm.Abp.IdentityManagement.Blazor.Server.BootstrapBlazorUI.csproj" />
		<ProjectReference Include="..\..\..\..\modules\BootstrapBlazorTheme\Rm.Abp.AspnetCore.Components.Server.BootstrapBlazorTheme\Rm.Abp.AspnetCore.Components.Server.BootstrapBlazorTheme.csproj" />
		<ProjectReference Include="..\..\..\..\modules\SettingManagement\Rm.Abp.SettingManagement.Blazor.Server.BootstrapBlazorUI\Rm.Abp.SettingManagement.Blazor.Server.BootstrapBlazorUI.csproj" />
		<ProjectReference Include="..\..\..\..\modules\TenantManagement\Rm.Abp.TenantManagement.Blazor.Server.BootstrapBlazorUI\Rm.Abp.TenantManagement.Blazor.Server.BootstrapBlazorUI.csproj" />
		<ProjectReference Include="..\..\src\BookStore.Application\BookStore.Application.csproj" />
		<ProjectReference Include="..\..\src\BookStore.HttpApi\BookStore.HttpApi.csproj" />
		<ProjectReference Include="..\..\src\BookStore.EntityFrameworkCore\BookStore.EntityFrameworkCore.csproj" />
		<PackageReference Include="Volo.Abp.Autofac" Version="8.2.1" />
		<PackageReference Include="Volo.Abp.Swashbuckle" Version="8.2.1" />
		<PackageReference Include="Volo.Abp.AspNetCore.Authentication.JwtBearer" Version="8.2.1" />
		<PackageReference Include="Volo.Abp.AspNetCore.Serilog" Version="8.2.1" />
	</ItemGroup>
	<ItemGroup>
		<Compile Remove="Logs\**" />
		<Content Remove="Logs\**" />
		<EmbeddedResource Remove="Logs\**" />
		<None Remove="Logs\**" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Pages\**\*.js">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Pages\**\*.css">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>