<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Version>9.3.2</Version>
    <MSVersion>9.0.5</MSVersion>
    <FodyVersion>6.9.2</FodyVersion>
    <!--TODO  <PackageIconUrl></PackageIconUrl> -->
    <PackageProjectUrl>https://github.com/rainmakerho/Rm.Abp.BootstrapBlazorUI</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/rainmakerho/Rm.Abp.BootstrapBlazorUI</RepositoryUrl>
  </PropertyGroup>
</Project>