<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Version>8.2.1.0</Version>
    <!--TODO  <PackageIconUrl></PackageIconUrl> -->
    <PackageProjectUrl>https://github.com/rainmakerho/Rm.Abp.BootstrapBlazorUI</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/rainmakerho/Rm.Abp.BootstrapBlazorUI</RepositoryUrl>
  </PropertyGroup>
</Project>